/*
 * cpp-terminfo
 * C++ standalone library for terminal terminfo capabilities.
 *
 * SPDX-FileCopyrightText: 2023-2024 cpp-terminfo
 *
 * SPDX-License-Identifier: MIT
 */

#include "cpp-terminfo/Capabilities.hpp"

#include <algorithm>
#include <stdexcept>

const std::array<Terminfo::BooleanCapability, Terminfo::Capabilities::m_booleans_size> Terminfo::Capabilities::m_booleans{
  // Booleans
  BooleanCapability{BooleanId::auto_left_margin, "bw", "cub1 wraps from column 0 to last column"},
  BooleanCapability{BooleanId::auto_right_margin, "am", "terminal has automatic margins"},
  BooleanCapability{BooleanId::no_esc_ctlc, "xsb", "beehive (f1=escape, f2=ctrl C)"},
  BooleanCapability{BooleanId::ceol_standout_glitch, "xhp", "standout not erased by overwriting (hp)"},
  BooleanCapability{BooleanId::eat_newline_glitch, "xenl", "newline ignored after 80 cols (concept)"},
  BooleanCapability{BooleanId::erase_overstrike, "eo", "can erase overstrikes with a blank"},
  BooleanCapability{BooleanId::generic_type, "gn", "generic line type"},
  BooleanCapability{BooleanId::hard_copy, "hc", "hardcopy terminal"},
  BooleanCapability{BooleanId::has_meta_key, "km", "Has a meta key (i.e., sets 8th-bit)"},
  BooleanCapability{BooleanId::has_status_line, "hs", "has extra status line"},
  BooleanCapability{BooleanId::insert_null_glitch, "in", "insert mode distinguishes nulls"},
  BooleanCapability{BooleanId::memory_above, "da", "display may be retained above the screen"},
  BooleanCapability{BooleanId::memory_below, "db", "display may be retained below the screen"},
  BooleanCapability{BooleanId::move_insert_mode, "mir", "safe to move while in insert mode"},
  BooleanCapability{BooleanId::move_standout_mode, "msgr", "safe to move while in standout mode"},
  BooleanCapability{BooleanId::over_strike, "os", "terminal can overstrike"},
  BooleanCapability{BooleanId::status_line_esc_ok, "eslok", "escape can be used on the status line"},
  BooleanCapability{BooleanId::dest_tabs_magic_smso, "xt", "tabs destructive, magic so char (t1061)"},
  BooleanCapability{BooleanId::tilde_glitch, "hz", "cannot print ~'s (Hazeltine)"},
  BooleanCapability{BooleanId::transparent_underline, "ul", "underline character overstrikes"},
  BooleanCapability{BooleanId::xon_xoff, "xon", "terminal uses xon/xoff handshaking"},
  BooleanCapability{BooleanId::needs_xon_xoff, "nxon", "padding will not work, xon/xoff required"},
  BooleanCapability{BooleanId::prtr_silent, "mc5i", "printer will not echo on screen"},
  BooleanCapability{BooleanId::hard_cursor, "chts", "cursor is hard to see"},
  BooleanCapability{BooleanId::non_rev_rmcup, "nrrmc", "smcup does not reverse rmcup"},
  BooleanCapability{BooleanId::no_pad_char, "npc", "pad character does not exist"},
  BooleanCapability{BooleanId::non_dest_scroll_region, "ndscr", "scrolling region is non-destructive"},
  BooleanCapability{BooleanId::can_change, "ccc", "terminal can re-define existing colors"},
  BooleanCapability{BooleanId::back_color_erase, "bce", "screen erased with background color"},
  BooleanCapability{BooleanId::hue_lightness_saturation, "hls", "terminal uses only HLS color notation (Tektronix)"},
  BooleanCapability{BooleanId::col_addr_glitch, "xhpa", "only positive motion for hpa/mhpa caps"},
  BooleanCapability{BooleanId::cr_cancels_micro_mode, "crxm", "using cr turns off micro mode"},
  BooleanCapability{BooleanId::has_print_wheel, "daisy", "printer needs operator to change character set"},
  BooleanCapability{BooleanId::row_addr_glitch, "xvpa", "only positive motion for vpa/mvpa caps"},
  BooleanCapability{BooleanId::semi_auto_right_margin, "sam", "printing in last column causes cr"},
  BooleanCapability{BooleanId::cpi_changes_res, "cpix", "changing character pitch changes resolution"},
  BooleanCapability{BooleanId::lpi_changes_res, "lpix", "changing line pitch changes resolution"},
};

const std::array<Terminfo::IntegerCapability, Terminfo::Capabilities::m_intergers_size> Terminfo::Capabilities::m_integers{
  // Integers
  IntegerCapability{IntegerId::columns, "cols", "number of columns in a line"},
  IntegerCapability{IntegerId::init_tabs, "it", "tabs initially every # spaces"},
  IntegerCapability{IntegerId::lines, "lines", "number of lines on screen or page"},
  IntegerCapability{IntegerId::lines_of_memory, "lm", "lines of memory if > line. 0 means varies"},
  IntegerCapability{IntegerId::magic_cookie_glitch, "xmc", "number of blank characters left by smso or rmso"},
  IntegerCapability{IntegerId::padding_baud_rate, "pb", "lowest baud rate where padding needed"},
  IntegerCapability{IntegerId::virtual_terminal, "vt", "virtual terminal number (CB/unix)"},
  IntegerCapability{IntegerId::width_status_line, "wsl", "number of columns in status line"},
  IntegerCapability{IntegerId::num_labels, "nlab", "number of labels on screen"},
  IntegerCapability{IntegerId::label_height, "lh", "rows in each label"},
  IntegerCapability{IntegerId::label_width, "lw", "columns in each label"},
  IntegerCapability{IntegerId::max_attributes, "ma", "maximum combined attributes terminal can handle"},
  IntegerCapability{IntegerId::maximum_windows, "wnum", "maximum number of definable windows"},
  IntegerCapability{IntegerId::max_colors, "colors", "maximum number of colors on screen"},
  IntegerCapability{IntegerId::max_pairs, "pairs", "maximum number of color-pairs on the screen"},
  IntegerCapability{IntegerId::no_color_video, "ncv", "video attributes that cannot be used with colors"},
  IntegerCapability{IntegerId::buffer_capacity, "bufsz", "numbers of bytes buffered before printing"},
  IntegerCapability{IntegerId::dot_vert_spacing, "spinv", "spacing of pins vertically in pins per inch"},
  IntegerCapability{IntegerId::dot_horz_spacing, "spinh", "spacing of dots horizontally in dots per inch"},
  IntegerCapability{IntegerId::max_micro_address, "maddr", "maximum value in micro_..._address"},
  IntegerCapability{IntegerId::max_micro_jump, "mjump", "maximum value in parm_..._micro"},
  IntegerCapability{IntegerId::micro_col_size, "mcs", "character step size when in micro mode"},
  IntegerCapability{IntegerId::micro_line_size, "mls", "line step size when in micro mode"},
  IntegerCapability{IntegerId::number_of_pins, "npins", "numbers of pins in print-head"},
  IntegerCapability{IntegerId::output_res_char, "orc", "horizontal resolution in units per line"},
  IntegerCapability{IntegerId::output_res_line, "orl", "vertical resolution in units per line"},
  IntegerCapability{IntegerId::output_res_horz_inch, "orhi", "horizontal resolution in units per inch"},
  IntegerCapability{IntegerId::output_res_vert_inch, "orvi", "vertical resolution in units per inch"},
  IntegerCapability{IntegerId::print_rate, "cps", "print rate in characters per second"},
  IntegerCapability{IntegerId::wide_char_size, "widcs", "character step size when in double wide mode"},
  IntegerCapability{IntegerId::buttons, "btns", "number of buttons on mouse"},
  IntegerCapability{IntegerId::bit_image_entwining, "bitwin", "number of passes for each bit-image row"},
  IntegerCapability{IntegerId::bit_image_type, "bitype", "type of bit-image device"},
};

const std::array<Terminfo::StringCapability, Terminfo::Capabilities::m_strings_size> Terminfo::Capabilities::m_strings = {
  // Strings
  StringCapability{StringId::back_tab, "cbt", "back tab (P)"},
  StringCapability{StringId::bell, "bel", "audible signal (bell) (P)"},
  StringCapability{StringId::carriage_return, "cr", "carriage return (P*) (P*)"},
  StringCapability{StringId::change_scroll_region, "csr", "change region to line #1 to line #2 (P)"},
  StringCapability{StringId::clear_all_tabs, "tbc", "clear all tab stops (P)"},
  StringCapability{StringId::clear_screen, "clear", "clear screen and home cursor (P*)"},
  StringCapability{StringId::clr_eol, "el", "clear to end of line (P)"},
  StringCapability{StringId::clr_eos, "ed", "clear to end of screen (P*)"},
  StringCapability{StringId::column_address, "hpa", "horizontal position #1, absolute (P)"},
  StringCapability{StringId::command_character, "cmdch", "terminal settable cmd character in prototype !?"},
  StringCapability{StringId::cursor_address, "cup", "move to row #1 columns #2"},
  StringCapability{StringId::cursor_down, "cud1", "down one line"},
  StringCapability{StringId::cursor_home, "home", "home cursor (if no cup)"},
  StringCapability{StringId::cursor_invisible, "civis", "make cursor invisible"},
  StringCapability{StringId::cursor_left, "cub1", "move left one space"},
  StringCapability{StringId::cursor_mem_address, "mrcup", "memory relative cursor addressing, move to row #1 columns #2"},
  StringCapability{StringId::cursor_normal, "cnorm", "make cursor appear normal (undo civis/cvvis)"},
  StringCapability{StringId::cursor_right, "cuf1", "non-destructive space (move right one space)"},
  StringCapability{StringId::cursor_to_ll, "ll", "last line, first column (if no cup)"},
  StringCapability{StringId::cursor_up, "cuu1", "up one line"},
  StringCapability{StringId::cursor_visible, "cvvis", "make cursor very visible"},
  StringCapability{StringId::delete_character, "dch1", "delete character (P*)"},
  StringCapability{StringId::delete_line, "dl1", "delete line (P*)"},
  StringCapability{StringId::dis_status_line, "dsl", "disable status line"},
  StringCapability{StringId::down_half_line, "hd", "half a line down"},
  StringCapability{StringId::enter_alt_charset_mode, "smacs", "start alternate character set (P)"},
  StringCapability{StringId::enter_blink_mode, "blink", "turn on blinking"},
  StringCapability{StringId::enter_bold_mode, "bold", "turn on bold (extra bright) mode"},
  StringCapability{StringId::enter_ca_mode, "smcup", "string to start programs using cup"},
  StringCapability{StringId::enter_delete_mode, "smdc", "enter delete mode"},
  StringCapability{StringId::enter_dim_mode, "dim", "turn on half-bright mode"},
  StringCapability{StringId::enter_insert_mode, "smir", "enter insert mode"},
  StringCapability{StringId::enter_secure_mode, "invis", "turn on blank mode (characters invisible)"},
  StringCapability{StringId::enter_protected_mode, "prot", "turn on protected mode"},
  StringCapability{StringId::enter_reverse_mode, "rev", "turn on reverse video mode"},
  StringCapability{StringId::enter_standout_mode, "smso", "begin standout mode"},
  StringCapability{StringId::enter_underline_mode, "smul", "begin underline mode"},
  StringCapability{StringId::erase_chars, "ech", "erase #1 characters (P)"},
  StringCapability{StringId::exit_alt_charset_mode, "rmacs", "end alternate character set (P)"},
  StringCapability{StringId::exit_attribute_mode, "sgr0", "turn off all attributes"},
  StringCapability{StringId::exit_ca_mode, "rmcup", "strings to end programs using cup"},
  StringCapability{StringId::exit_delete_mode, "rmdc", "end delete mode"},
  StringCapability{StringId::exit_insert_mode, "rmir", "exit insert mode"},
  StringCapability{StringId::exit_standout_mode, "rmso", "exit standout mode"},
  StringCapability{StringId::exit_underline_mode, "rmul", "exit underline mode"},
  StringCapability{StringId::flash_screen, "flash", "visible bell (may not move cursor)"},
  StringCapability{StringId::form_feed, "ff", "hardcopy terminal page eject (P*)"},
  StringCapability{StringId::from_status_line, "fsl", "return from status line"},
  StringCapability{StringId::init_1string, "is1", "initialization string"},
  StringCapability{StringId::init_2string, "is2", "initialization string"},
  StringCapability{StringId::init_3string, "is3", "initialization string"},
  StringCapability{StringId::init_file, "if", "name of initialization file"},
  StringCapability{StringId::insert_character, "ich1", "insert character (P)"},
  StringCapability{StringId::insert_line, "il1", "insert line (P*)"},
  StringCapability{StringId::insert_padding, "ip", "insert padding after inserted character"},
  StringCapability{StringId::key_backspace, "kbs", "backspace key"},
  StringCapability{StringId::key_catab, "ktbc", "clear-all-tabs key"},
  StringCapability{StringId::key_clear, "kclr", "clear-screen or erase key"},
  StringCapability{StringId::key_ctab, "kctab", "clear-tab key"},
  StringCapability{StringId::key_dc, "kdch1", "delete-character key"},
  StringCapability{StringId::key_dl, "kdl1", "delete-line key"},
  StringCapability{StringId::key_down, "kcud1", "down-arrow key"},
  StringCapability{StringId::key_eic, "krmir", "sent by rmir or smir in insert mode"},
  StringCapability{StringId::key_eol, "kel", "clear-to-end-of-line key"},
  StringCapability{StringId::key_eos, "ked", "clear-to-end-of-screen key"},
  StringCapability{StringId::key_f0, "kf0", "F0 function key"},
  StringCapability{StringId::key_f1, "kf1", "F1 function key"},
  StringCapability{StringId::key_f10, "kf10", "F10 function key"},
  StringCapability{StringId::key_f2, "kf2", "F2 function key"},
  StringCapability{StringId::key_f3, "kf3", "F3 function key"},
  StringCapability{StringId::key_f4, "kf4", "F4 function key"},
  StringCapability{StringId::key_f5, "kf5", "F5 function key"},
  StringCapability{StringId::key_f6, "kf6", "F6 function key"},
  StringCapability{StringId::key_f7, "kf7", "F7 function key"},
  StringCapability{StringId::key_f8, "kf8", "F8 function key"},
  StringCapability{StringId::key_f9, "kf9", "F9 function key"},
  StringCapability{StringId::key_home, "khome", "home key"},
  StringCapability{StringId::key_ic, "kich1", "insert-character key"},
  StringCapability{StringId::key_il, "kil1", "insert-line key"},
  StringCapability{StringId::key_left, "kcub1", "left-arrow key"},
  StringCapability{StringId::key_ll, "kll", "lower-left key (home down)"},
  StringCapability{StringId::key_npage, "knp", "next-page key"},
  StringCapability{StringId::key_ppage, "kpp", "previous-page key"},
  StringCapability{StringId::key_right, "kcuf1", "right-arrow key"},
  StringCapability{StringId::key_sf, "kind", "scroll-forward key"},
  StringCapability{StringId::key_sr, "kri", "scroll-backward key"},
  StringCapability{StringId::key_stab, "khts", "set-tab key"},
  StringCapability{StringId::key_up, "kcuu1", "up-arrow key"},
  StringCapability{StringId::keypad_local, "rmkx", "leave keyboard transmit mode"},
  StringCapability{StringId::keypad_xmit, "smkx", "enter keyboard transmit mode"},
  StringCapability{StringId::lab_f0, "lf0", "label on function key f0 if not f0"},
  StringCapability{StringId::lab_f1, "lf1", "label on function key f1 if not f1"},
  StringCapability{StringId::lab_f10, "lf10", "label on function key f10 if not f10"},
  StringCapability{StringId::lab_f2, "lf2", "label on function key f2 if not f2"},
  StringCapability{StringId::lab_f3, "lf3", "label on function key f3 if not f3"},
  StringCapability{StringId::lab_f4, "lf4", "label on function key f4 if not f4"},
  StringCapability{StringId::lab_f5, "lf5", "label on function key f5 if not f5"},
  StringCapability{StringId::lab_f6, "lf6", "label on function key f6 if not f6"},
  StringCapability{StringId::lab_f7, "lf7", "label on function key f7 if not f7"},
  StringCapability{StringId::lab_f8, "lf8", "label on function key f8 if not f8"},
  StringCapability{StringId::lab_f9, "lf9", "label on function key f9 if not f9"},
  StringCapability{StringId::meta_off, "rmm", "turn off meta mode"},
  StringCapability{StringId::meta_on, "smm", "turn on meta mode (8th-bit on)"},
  StringCapability{StringId::newline, "nel", "newline (behave like cr followed by lf)"},
  StringCapability{StringId::pad_char, "pad", "padding char (instead of null)"},
  StringCapability{StringId::parm_dch, "dch", "delete #1 characters (P*)"},
  StringCapability{StringId::parm_delete_line, "dl", "delete #1 lines (P*)"},
  StringCapability{StringId::parm_down_cursor, "cud", "down #1 lines (P*)"},
  StringCapability{StringId::parm_ich, "ich", "insert #1 characters (P*)"},
  StringCapability{StringId::parm_index, "indn", "scroll forward #1 lines (P)"},
  StringCapability{StringId::parm_insert_line, "il", "insert #1 lines (P*)"},
  StringCapability{StringId::parm_left_cursor, "cub", "move #1 characters to the left (P)"},
  StringCapability{StringId::parm_right_cursor, "cuf", "move #1 characters to the right (P*)"},
  StringCapability{StringId::parm_rindex, "rin", "scroll back #1 lines (P)"},
  StringCapability{StringId::parm_up_cursor, "cuu", "up #1 lines (P*)"},
  StringCapability{StringId::pkey_key, "pfkey", "program function key #1 to type string #2"},
  StringCapability{StringId::pkey_local, "pfloc", "program function key #1 to execute string #2"},
  StringCapability{StringId::pkey_xmit, "pfx", "program function key #1 to transmit string #2"},
  StringCapability{StringId::print_screen, "mc0", "print contents of screen"},
  StringCapability{StringId::prtr_off, "mc4", "turn off printer"},
  StringCapability{StringId::repeat_char, "rep", "repeat char #1 #2 times (P*)"},
  StringCapability{StringId::reset_1string, "rs1", "reset string"},
  StringCapability{StringId::reset_2string, "rs2", "reset string"},
  StringCapability{StringId::reset_3string, "rs3", "reset string"},
  StringCapability{StringId::reset_file, "rf", "name of reset file"},
  StringCapability{StringId::restore_cursor, "rc", "restore cursor to position of last save_cursor"},
  StringCapability{StringId::row_address, "vpa", "vertical position #1 absolute (P)"},
  StringCapability{StringId::save_cursor, "sc", "save current cursor position (P)"},
  StringCapability{StringId::scroll_forward, "ind", "scroll text up (P)"},
  StringCapability{StringId::scroll_reverse, "ri", "scroll text down (P)"},
  StringCapability{StringId::set_attributes, "sgr", "define video attributes #1-#9 (PG9)"},
  StringCapability{StringId::set_tab, "hts", "set a tab in every row, current columns"},
  StringCapability{StringId::set_window, "wind", "current window is lines #1-#2 cols #3-#4"},
  StringCapability{StringId::tab, "ht", "tab to next 8-space hardware tab stop"},
  StringCapability{StringId::to_status_line, "tsl", "move to status line, column #1"},
  StringCapability{StringId::underline_char, "uc", "underline char and move past it"},
  StringCapability{StringId::up_half_line, "hu", "half a line up"},
  StringCapability{StringId::init_prog, "iprog", "path name of program for initialization"},
  StringCapability{StringId::key_a1, "ka1", "upper left of keypad"},
  StringCapability{StringId::key_a3, "ka3", "upper right of keypad"},
  StringCapability{StringId::key_b2, "kb2", "center of keypad"},
  StringCapability{StringId::key_c1, "kc1", "lower left of keypad"},
  StringCapability{StringId::key_c3, "kc3", "lower right of keypad"},
  StringCapability{StringId::prtr_non, "mc5p", "turn on printer for #1 bytes"},
  StringCapability{StringId::char_padding, "rmp", "like ip but when in insert mode"},
  StringCapability{StringId::acs_chars, "acsc", "graphics charset pairs, based on vt100"},
  StringCapability{StringId::plab_norm, "pln", "program label #1 to show string #2"},
  StringCapability{StringId::key_btab, "kcbt", "back-tab key"},
  StringCapability{StringId::enter_xon_mode, "smxon", "turn on xon/xoff handshaking"},
  StringCapability{StringId::exit_xon_mode, "rmxon", "turn off xon/xoff handshaking"},
  StringCapability{StringId::enter_am_mode, "smam", "turn on automatic margins"},
  StringCapability{StringId::exit_am_mode, "rmam", "turn off automatic margins"},
  StringCapability{StringId::xon_character, "xonc", "XON character"},
  StringCapability{StringId::xoff_character, "xoffc", "XOFF character"},
  StringCapability{StringId::ena_acs, "enacs", "enable alternate char set"},
  StringCapability{StringId::label_on, "smln", "turn on soft labels"},
  StringCapability{StringId::label_off, "rmln", "turn off soft labels"},
  StringCapability{StringId::key_beg, "kbeg", "begin key"},
  StringCapability{StringId::key_cancel, "kcan", "cancel key"},
  StringCapability{StringId::key_close, "kclo", "close key"},
  StringCapability{StringId::key_command, "kcmd", "command key"},
  StringCapability{StringId::key_copy, "kcpy", "copy key"},
  StringCapability{StringId::key_create, "kcrt", "create key"},
  StringCapability{StringId::key_end, "kend", "end key"},
  StringCapability{StringId::key_enter, "kent", "enter/send key"},
  StringCapability{StringId::key_exit, "kext", "exit key"},
  StringCapability{StringId::key_find, "kfnd", "find key"},
  StringCapability{StringId::key_help, "khlp", "help key"},
  StringCapability{StringId::key_mark, "kmrk", "mark key"},
  StringCapability{StringId::key_message, "kmsg", "message key"},
  StringCapability{StringId::key_move, "kmov", "move key"},
  StringCapability{StringId::key_next, "knxt", "next key"},
  StringCapability{StringId::key_open, "kopn", "open key"},
  StringCapability{StringId::key_options, "kopt", "options key"},
  StringCapability{StringId::key_previous, "kprv", "previous key"},
  StringCapability{StringId::key_print, "kprt", "print key"},
  StringCapability{StringId::key_redo, "krdo", "redo key"},
  StringCapability{StringId::key_reference, "kref", "reference key"},
  StringCapability{StringId::key_refresh, "krfr", "refresh key"},
  StringCapability{StringId::key_replace, "krpl", "replace key"},
  StringCapability{StringId::key_restart, "krst", "restart key"},
  StringCapability{StringId::key_resume, "kres", "resume key"},
  StringCapability{StringId::key_save, "ksav", "save key"},
  StringCapability{StringId::key_suspend, "kspd", "suspend key"},
  StringCapability{StringId::key_undo, "kund", "undo key"},
  StringCapability{StringId::key_sbeg, "kBEG", "shifted begin key"},
  StringCapability{StringId::key_scancel, "kCAN", "shifted cancel key"},
  StringCapability{StringId::key_scommand, "kCMD", "shifted command key"},
  StringCapability{StringId::key_scopy, "kCPY", "shifted copy key"},
  StringCapability{StringId::key_screate, "kCRT", "shifted create key"},
  StringCapability{StringId::key_sdc, "kDC", "shifted delete-character key"},
  StringCapability{StringId::key_sdl, "kDL", "shifted delete-line key"},
  StringCapability{StringId::key_select, "kslt", "select key"},
  StringCapability{StringId::key_send, "kEND", "shifted end key"},
  StringCapability{StringId::key_seol, "kEOL", "shifted clear-to-end-of-line key"},
  StringCapability{StringId::key_sexit, "kEXT", "shifted exit key"},
  StringCapability{StringId::key_sfind, "kFND", "shifted find key"},
  StringCapability{StringId::key_shelp, "kHLP", "shifted help key"},
  StringCapability{StringId::key_shome, "kHOM", "shifted home key"},
  StringCapability{StringId::key_sic, "kIC", "shifted insert-character key"},
  StringCapability{StringId::key_sleft, "kLFT", "shifted left-arrow key"},
  StringCapability{StringId::key_smessage, "kMSG", "shifted message key"},
  StringCapability{StringId::key_smove, "kMOV", "shifted move key"},
  StringCapability{StringId::key_snext, "kNXT", "shifted next key"},
  StringCapability{StringId::key_soptions, "kOPT", "shifted options key"},
  StringCapability{StringId::key_sprevious, "kPRV", "shifted previous key"},
  StringCapability{StringId::key_sprint, "kPRT", "shifted print key"},
  StringCapability{StringId::key_sredo, "kRDO", "shifted redo key"},
  StringCapability{StringId::key_sreplace, "kRPL", "shifted replace key"},
  StringCapability{StringId::key_sright, "kRIT", "shifted right-arrow key"},
  StringCapability{StringId::key_srsume, "kRES", "shifted resume key"},
  StringCapability{StringId::key_ssave, "kSAV", "shifted save key"},
  StringCapability{StringId::key_ssuspend, "kSPD", "shifted suspend key"},
  StringCapability{StringId::key_sundo, "kUND", "shifted undo key"},
  StringCapability{StringId::req_for_input, "rfi", "send next input char (for ptys)"},
  StringCapability{StringId::key_f11, "kf11", "F11 function key"},
  StringCapability{StringId::key_f12, "kf12", "F12 function key"},
  StringCapability{StringId::key_f13, "kf13", "F13 function key"},
  StringCapability{StringId::key_f14, "kf14", "F14 function key"},
  StringCapability{StringId::key_f15, "kf15", "F15 function key"},
  StringCapability{StringId::key_f16, "kf16", "F16 function key"},
  StringCapability{StringId::key_f17, "kf17", "F17 function key"},
  StringCapability{StringId::key_f18, "kf18", "F18 function key"},
  StringCapability{StringId::key_f19, "kf19", "F19 function key"},
  StringCapability{StringId::key_f20, "kf20", "F20 function key"},
  StringCapability{StringId::key_f21, "kf21", "F21 function key"},
  StringCapability{StringId::key_f22, "kf22", "F22 function key"},
  StringCapability{StringId::key_f23, "kf23", "F23 function key"},
  StringCapability{StringId::key_f24, "kf24", "F24 function key"},
  StringCapability{StringId::key_f25, "kf25", "F25 function key"},
  StringCapability{StringId::key_f26, "kf26", "F26 function key"},
  StringCapability{StringId::key_f27, "kf27", "F27 function key"},
  StringCapability{StringId::key_f28, "kf28", "F28 function key"},
  StringCapability{StringId::key_f29, "kf29", "F29 function key"},
  StringCapability{StringId::key_f30, "kf30", "F30 function key"},
  StringCapability{StringId::key_f31, "kf31", "F31 function key"},
  StringCapability{StringId::key_f32, "kf32", "F32 function key"},
  StringCapability{StringId::key_f33, "kf33", "F33 function key"},
  StringCapability{StringId::key_f34, "kf34", "F34 function key"},
  StringCapability{StringId::key_f35, "kf35", "F35 function key"},
  StringCapability{StringId::key_f36, "kf36", "F36 function key"},
  StringCapability{StringId::key_f37, "kf37", "F37 function key"},
  StringCapability{StringId::key_f38, "kf38", "F38 function key"},
  StringCapability{StringId::key_f39, "kf39", "F39 function key"},
  StringCapability{StringId::key_f40, "kf40", "F40 function key"},
  StringCapability{StringId::key_f41, "kf41", "F41 function key"},
  StringCapability{StringId::key_f42, "kf42", "F42 function key"},
  StringCapability{StringId::key_f43, "kf43", "F43 function key"},
  StringCapability{StringId::key_f44, "kf44", "F44 function key"},
  StringCapability{StringId::key_f45, "kf45", "F45 function key"},
  StringCapability{StringId::key_f46, "kf46", "F46 function key"},
  StringCapability{StringId::key_f47, "kf47", "F47 function key"},
  StringCapability{StringId::key_f48, "kf48", "F48 function key"},
  StringCapability{StringId::key_f49, "kf49", "F49 function key"},
  StringCapability{StringId::key_f50, "kf50", "F50 function key"},
  StringCapability{StringId::key_f51, "kf51", "F51 function key"},
  StringCapability{StringId::key_f52, "kf52", "F52 function key"},
  StringCapability{StringId::key_f53, "kf53", "F53 function key"},
  StringCapability{StringId::key_f54, "kf54", "F54 function key"},
  StringCapability{StringId::key_f55, "kf55", "F55 function key"},
  StringCapability{StringId::key_f56, "kf56", "F56 function key"},
  StringCapability{StringId::key_f57, "kf57", "F57 function key"},
  StringCapability{StringId::key_f58, "kf58", "F58 function key"},
  StringCapability{StringId::key_f59, "kf59", "F59 function key"},
  StringCapability{StringId::key_f60, "kf60", "F60 function key"},
  StringCapability{StringId::key_f61, "kf61", "F61 function key"},
  StringCapability{StringId::key_f62, "kf62", "F62 function key"},
  StringCapability{StringId::key_f63, "kf63", "F63 function key"},
  StringCapability{StringId::clr_bol, "el1", "Clear to beginning of line"},
  StringCapability{StringId::clear_margins, "mgc", "clear right and left soft margins"},
  StringCapability{StringId::set_left_margin, "smgl", "set left soft margin at current column (not in BSD termcap)"},
  StringCapability{StringId::set_right_margin, "smgr", "set right soft margin at current column"},
  StringCapability{StringId::label_format, "fln", "label format"},
  StringCapability{StringId::set_clock, "sclk", "set clock, #1 hrs #2 mins #3 secs"},
  StringCapability{StringId::display_clock, "dclk", "display clock"},
  StringCapability{StringId::remove_clock, "rmclk", "remove clock"},
  StringCapability{StringId::create_window, "cwin", "define a window #1 from #2,#3 to #4,#5"},
  StringCapability{StringId::goto_window, "wingo", "go to window #1"},
  StringCapability{StringId::hangup, "hup", "hang-up phone"},
  StringCapability{StringId::dial_phone, "dial", "dial number #1"},
  StringCapability{StringId::quick_dial, "qdial", "dial number #1 without checking"},
  StringCapability{StringId::tone, "tone", "select touch tone dialing"},
  StringCapability{StringId::pulse, "pulse", "select pulse dialing"},
  StringCapability{StringId::flash_hook, "hook", "flash switch hook"},
  StringCapability{StringId::fixed_pause, "pause", "pause for 2-3 seconds"},
  StringCapability{StringId::wait_tone, "wait", "wait for dial-tone"},
  StringCapability{StringId::user0, "u0", "User string #0"},
  StringCapability{StringId::user1, "u1", "User string #1"},
  StringCapability{StringId::user2, "u2", "User string #2"},
  StringCapability{StringId::user3, "u3", "User string #3"},
  StringCapability{StringId::user4, "u4", "User string #4"},
  StringCapability{StringId::user5, "u5", "User string #5"},
  StringCapability{StringId::user6, "u6", "User string #6"},
  StringCapability{StringId::user7, "u7", "User string #7"},
  StringCapability{StringId::user8, "u8", "User string #8"},
  StringCapability{StringId::user9, "u9", "User string #9"},
  StringCapability{StringId::orig_pair, "op", "Set default pair to its original value"},
  StringCapability{StringId::orig_colors, "oc", "Set all color pairs to the original ones"},
  StringCapability{StringId::initialize_color, "initc", "initialize color #1 to (#2,#3,#4)"},
  StringCapability{StringId::initialize_pair, "initp", "Initialize color pair #1 to fg=(#2,#3,#4), bg=(#5,#6,#7)"},
  StringCapability{StringId::set_color_pair, "scp", "Set current color pair to #1"},
  StringCapability{StringId::set_foreground, "setf", "Set foreground color #1"},
  StringCapability{StringId::set_background, "setb", "Set background color #1"},
  StringCapability{StringId::change_char_pitch, "cpi", "Change number of characters per inch to #1"},
  StringCapability{StringId::change_line_pitch, "lpi", "Change number of lines per inch to #1"},
  StringCapability{StringId::change_res_horz, "chr", "Change horizontal resolution to #1"},
  StringCapability{StringId::change_res_vert, "cvr", "Change vertical resolution to #1"},
  StringCapability{StringId::define_char, "defc", "Define a character #1, #2 dots wide, descender #3"},
  StringCapability{StringId::enter_doublewide_mode, "swidm", "Enter double-wide mode"},
  StringCapability{StringId::enter_draft_quality, "sdrfq", "Enter draft-quality mode"},
  StringCapability{StringId::enter_italics_mode, "sitm", "Enter italic mode"},
  StringCapability{StringId::enter_leftward_mode, "slm", "Start leftward carriage motion"},
  StringCapability{StringId::enter_micro_mode, "smicm", "Start micro-motion mode"},
  StringCapability{StringId::enter_near_letter_quality, "snlq", "Enter NLQ mode"},
  StringCapability{StringId::enter_normal_quality, "snrmq", "Enter normal-quality mode"},
  StringCapability{StringId::enter_shadow_mode, "sshm", "Enter shadow-print mode"},
  StringCapability{StringId::enter_subscript_mode, "ssubm", "Enter subscript mode"},
  StringCapability{StringId::enter_superscript_mode, "ssupm", "Enter superscript mode"},
  StringCapability{StringId::enter_upward_mode, "sum", "Start upward carriage motion"},
  StringCapability{StringId::exit_doublewide_mode, "rwidm", "End double-wide mode"},
  StringCapability{StringId::exit_italics_mode, "ritm", "End italic mode"},
  StringCapability{StringId::exit_leftward_mode, "rlm", "End left-motion mode"},
  StringCapability{StringId::exit_micro_mode, "rmicm", "End micro-motion mode"},
  StringCapability{StringId::exit_shadow_mode, "rshm", "End shadow-print mode"},
  StringCapability{StringId::exit_subscript_mode, "rsubm", "End subscript mode"},
  StringCapability{StringId::exit_superscript_mode, "rsupm", "End superscript mode"},
  StringCapability{StringId::exit_upward_mode, "rum", "End reverse character motion"},
  StringCapability{StringId::micro_column_address, "mhpa", "Like column_address in micro mode"},
  StringCapability{StringId::micro_down, "mcud1", "Like cursor_down in micro mode"},
  StringCapability{StringId::micro_left, "mcub1", "Like cursor_left in micro mode"},
  StringCapability{StringId::micro_right, "mcuf1", "Like cursor_right in micro mode"},
  StringCapability{StringId::micro_row_address, "mvpa", "Like row_address #1 in micro mode"},
  StringCapability{StringId::micro_up, "mcuu1", "Like cursor_up in micro mode"},
  StringCapability{StringId::order_of_pins, "porder", "Match software bits to print-head pins"},
  StringCapability{StringId::parm_down_micro, "mcud", "Like parm_down_cursor in micro mode"},
  StringCapability{StringId::parm_left_micro, "mcub", "Like parm_left_cursor in micro mode"},
  StringCapability{StringId::parm_right_micro, "mcuf", "Like parm_right_cursor in micro mode"},
  StringCapability{StringId::parm_up_micro, "mcuu", "Like parm_up_cursor in micro mode"},
  StringCapability{StringId::select_char_set, "scs", "Select character set, #1"},
  StringCapability{StringId::set_bottom_margin, "smgb", "Set bottom margin at current line"},
  StringCapability{StringId::set_bottom_margin_parm, "smgbp", "Set bottom margin at line #1 or (if smgtp is not given) #2 lines from bottom"},
  StringCapability{StringId::set_left_margin_parm, "smglp", "Set left (right) margin at column #1"},
  StringCapability{StringId::set_right_margin_parm, "smgrp", "Set right margin at column #1"},
  StringCapability{StringId::set_top_margin, "smgt", "Set top margin at current line"},
  StringCapability{StringId::set_top_margin_parm, "smgtp", "Set top (bottom) margin at row #1"},
  StringCapability{StringId::start_bit_image, "sbim", "Start printing bit image graphics"},
  StringCapability{StringId::start_char_set_def, "scsd", "Start character set definition #1, with #2 characters in the set"},
  StringCapability{StringId::stop_bit_image, "rbim", "Stop printing bit image graphics"},
  StringCapability{StringId::stop_char_set_def, "rcsd", "End definition of character set #1"},
  StringCapability{StringId::subscript_characters, "subcs", "List of subscriptable characters"},
  StringCapability{StringId::superscript_characters, "supcs", "List of superscriptable characters"},
  StringCapability{StringId::these_cause_cr, "docr", "Printing any of these characters causes CR"},
  StringCapability{StringId::zero_motion, "zerom", "No motion for subsequent character"},
  StringCapability{StringId::char_set_names, "csnm", "Produce #1'th item from list of character set names"},
  StringCapability{StringId::key_mouse, "kmous", "Mouse event has occurred"},
  StringCapability{StringId::mouse_info, "minfo", "Mouse status information"},
  StringCapability{StringId::req_mouse_pos, "reqmp", "Request mouse position"},
  StringCapability{StringId::get_mouse, "getm", "Curses should get button events, parameter #1 not documented."},
  StringCapability{StringId::set_a_foreground, "setaf", "Set foreground color to #1, using ANSI escape"},
  StringCapability{StringId::set_a_background, "setab", "Set background color to #1, using ANSI escape"},
  StringCapability{StringId::pkey_plab, "pfxl", "Program function key #1 to type string #2 and show string #3"},
  StringCapability{StringId::device_type, "devt", "Indicate language, codeset support"},
  StringCapability{StringId::code_set_init, "csin", "Init sequence for multiple codesets"},
  StringCapability{StringId::set0_des_seq, "s0ds", "Shift to codeset 0 (EUC set 0, ASCII)"},
  StringCapability{StringId::set1_des_seq, "s1ds", "Shift to codeset 1"},
  StringCapability{StringId::set2_des_seq, "s2ds", "Shift to codeset 2"},
  StringCapability{StringId::set3_des_seq, "s3ds", "Shift to codeset 3"},
  StringCapability{StringId::set_lr_margin, "smglr", "Set both left and right margins to #1, #2.  (ML is not in BSD termcap)."},
  StringCapability{StringId::set_tb_margin, "smgtb", "Sets both top and bottom margins to #1, #2"},
  StringCapability{StringId::bit_image_repeat, "birep", "Repeat bit image cell #1 #2 times"},
  StringCapability{StringId::bit_image_newline, "binel", "Move to next row of the bit image"},
  StringCapability{StringId::bit_image_carriage_return, "bicr", "Move to beginning of same row"},
  StringCapability{StringId::color_names, "colornm", "Give name for color #1"},
  StringCapability{StringId::define_bit_image_region, "defbi", "Define rectangular bit image region"},
  StringCapability{StringId::end_bit_image_region, "endbi", "End a bit-image region"},
  StringCapability{StringId::set_color_band, "setcolor", "Change to ribbon color #1"},
  StringCapability{StringId::set_page_length, "slines", "Set page length to #1 lines"},
  StringCapability{StringId::display_pc_char, "dispc", "Display PC character #1"},
  StringCapability{StringId::enter_pc_charset_mode, "smpch", "Enter PC character display mode"},
  StringCapability{StringId::exit_pc_charset_mode, "rmpch", "Exit PC character display mode"},
  StringCapability{StringId::enter_scancode_mode, "smsc", "Enter PC scancode mode"},
  StringCapability{StringId::exit_scancode_mode, "rmsc", "Exit PC scancode mode"},
  StringCapability{StringId::pc_term_options, "pctrm", "PC terminal options"},
  StringCapability{StringId::scancode_escape, "scesc", "Escape for scancode emulation"},
  StringCapability{StringId::alt_scancode_esc, "scesa", "Alternate escape for scancode emulation"},
  StringCapability{StringId::enter_horizontal_hl_mode, "ehhlm", "Enter horizontal highlight mode"},
  StringCapability{StringId::enter_left_hl_mode, "elhlm", "Enter left highlight mode"},
  StringCapability{StringId::enter_low_hl_mode, "elohlm", "Enter low highlight mode"},
  StringCapability{StringId::enter_right_hl_mode, "erhlm", "Enter right highlight mode"},
  StringCapability{StringId::enter_top_hl_mode, "ethlm", "Enter top highlight mode"},
  StringCapability{StringId::enter_vertical_hl_mode, "evhlm", "Enter vertical highlight mode"},
  StringCapability{StringId::set_a_attributes, "sgr1", "Define second set of video attributes #1-#6"},
  StringCapability{StringId::set_pglen_inch, "slength", "Set page length to #1 hundredth of an inch (some implementations use sL for termcap)."},
  // Others
  StringCapability{StringId::set_underline_color, "setal", "set (under)line color"},
  StringCapability{StringId::lock_memory_above_cursor, "meml", "locks memory above the cursor (ala HP terminals)"},
  StringCapability{StringId::unlock_memory_above_cursor, "memu", "unlocks memory above the cursor (ala HP terminals)"},
  StringCapability{StringId::enable_real_bold, "gsbom", " enable real bold (not intensity bright) mode"},
  StringCapability{StringId::disable_real_bold, "grbom", "disable real bold (not intensity bright) mode"},
  StringCapability{StringId::mouse_response, "xm", "describes the mouse response"},
  StringCapability{StringId::enable_focus_events, "fe", "enables focus events"},
  StringCapability{StringId::disable_focus_events, "fd", "disables focus events"},
  StringCapability{StringId::turn_on_printer, "mc5", "turn on printer"},
  StringCapability{StringId::set_cursor_color, "Cs", "set cursor color"},
  StringCapability{StringId::reset_cursor_color, "Cr", "reset cursor color"},
  StringCapability{StringId::modify_selection_clipboard, "Ms", "modifies the selection/clipboard"},
};

Terminfo::BooleanId Terminfo::Capabilities::getBoolean(const std::string& str)
{
  const boolean_const_iterator found = std::find(m_booleans.begin(), m_booleans.end(), str);
  if(found != m_booleans.end()) return found->id();
  throw std::out_of_range(str);
}

Terminfo::IntegerId Terminfo::Capabilities::getInteger(const std::string& str)
{
  const integer_const_iterator found = std::find(m_integers.begin(), m_integers.end(), str);
  if(std::find(m_integers.begin(), m_integers.end(), str) != m_integers.end()) return found->id();
  throw std::out_of_range(str);
}

Terminfo::StringId Terminfo::Capabilities::getString(const std::string& str)
{
  const string_const_iterator found = std::find(m_strings.begin(), m_strings.end(), str);
  if(found != m_strings.end()) return found->id();
  throw std::out_of_range(str);
}
